spring:
  db:
    url: jdbc:h2:mem:testDB
    user: sa
    password:


#NEWS_DB_URL: jdbc:h2:mem:testDB
#NEWS_DB_USER: SA
#NEWS_DB_PASSWORD:

springdoc:
  show-login-endpoint: true
  enable-spring-security: true
  show-oauth2-endpoints: true
  swagger-ui.csrf.enabled: true